Use monkeypatch instead of setting method
This is more idiomatic for tests, and otherwise mypy would complain about "tests/test_universe.py:86: error: Cannot assign to a method  [method-assign]"